/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 15 02:20:03 GMT 2024
 */

package com.example;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.example.Banco;
import com.example.Conta;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Banco_ESTest extends Banco_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Banco banco0 = new Banco();
      Conta conta0 = new Conta();
      Long long0 = new Long(0L);
      Double double0 = new Double(0L);
      Conta conta1 = new Conta(long0, "", banco0, double0, 0, '{');
      Boolean boolean0 = banco0.transferencia(conta0, conta1, double0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Banco banco0 = new Banco();
      String string0 = banco0.getNome();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Long long0 = new Long(0L);
      LinkedList<Conta> linkedList0 = new LinkedList<Conta>();
      Banco banco0 = new Banco(long0, "", linkedList0);
      String string0 = banco0.getNome();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Long long0 = new Long(0L);
      Banco banco0 = new Banco("9@Q`v]${sf0XM");
      List<Conta> list0 = banco0.getContas();
      Banco banco1 = new Banco(long0, "9@Q`v]${sf0XM", list0);
      Long long1 = banco1.getId();
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Long long0 = new Long(2917L);
      Banco banco0 = new Banco(", digitoVerificador=");
      List<Conta> list0 = banco0.getContas();
      Banco banco1 = new Banco(long0, "", list0);
      Long long1 = banco1.getId();
      assertEquals(2917L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Long long0 = new Long((-1L));
      LinkedList<Conta> linkedList0 = new LinkedList<Conta>();
      Banco banco0 = new Banco(long0, "R?!*#;j<", linkedList0);
      Long long1 = banco0.getId();
      assertEquals((-1L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Banco banco0 = new Banco();
      List<Conta> list0 = banco0.getContas();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Long long0 = new Long(2917L);
      Banco banco0 = new Banco(", digitoVerificador=");
      banco0.addContaById(long0);
      List<Conta> list0 = banco0.getContas();
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Long long0 = new Long(5422L);
      LinkedList<Conta> linkedList0 = new LinkedList<Conta>();
      Banco banco0 = new Banco(long0, "", linkedList0);
      boolean boolean0 = banco0.canEqual(banco0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Banco banco0 = new Banco("IsxKq5;A.C|yf><';x");
      boolean boolean0 = banco0.canEqual("IsxKq5;A.C|yf><';x");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Long long0 = new Long((-2124L));
      Banco banco0 = new Banco("Ktf!!<Fr~y?a{fgw+z");
      Conta conta0 = new Conta(long0);
      // Undeclared exception!
      try { 
        banco0.transferencia(conta0, conta0, (Double) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.example.Banco", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Long long0 = new Long(2013L);
      Banco banco0 = new Banco(long0, ", nome=", (List<Conta>) null);
      // Undeclared exception!
      try { 
        banco0.addContaById((Long) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.example.Banco", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Banco banco0 = new Banco();
      Conta conta0 = new Conta();
      // Undeclared exception!
      try { 
        banco0.addConta(conta0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.example.Banco", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Banco banco0 = new Banco(", banco=");
      String string0 = banco0.getNome();
      assertEquals(", banco=", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Banco banco0 = new Banco(", banco=");
      Long long0 = banco0.getId();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Banco banco0 = new Banco(", banco=");
      Conta conta0 = new Conta();
      Double double0 = new Double(666.7);
      Boolean boolean0 = banco0.transferencia(conta0, conta0, double0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Banco banco0 = new Banco("/Y@e{Cc~ 8rm~,8X~W");
      Banco banco1 = new Banco("/Y@e{Cc~ 8rm~,8X~W");
      assertTrue(banco1.equals((Object)banco0));
      
      Long long0 = new Long(0L);
      banco0.addContaById(long0);
      boolean boolean0 = banco0.equals(banco1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Banco banco0 = new Banco("/Y@e{Cc~ 8rm~,8X~W");
      Banco banco1 = new Banco("/Y@e{Cc~ 8rm~,8X~W");
      assertTrue(banco1.equals((Object)banco0));
      
      banco0.setContas((List<Conta>) null);
      boolean boolean0 = banco0.equals(banco1);
      assertFalse(banco1.equals((Object)banco0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Banco banco0 = new Banco("/Y@e{Cc~ 8rm~,8X~W");
      Banco banco1 = new Banco("/Y@e{Cc~ 8rm~,8X~W");
      boolean boolean0 = banco0.equals(banco1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Long long0 = new Long(210L);
      LinkedList<Conta> linkedList0 = new LinkedList<Conta>();
      Banco banco0 = new Banco(long0, "`AA 71*P.mBl^yqU", linkedList0);
      Banco banco1 = new Banco("Banco(id=");
      banco1.setId(long0);
      boolean boolean0 = banco0.equals(banco1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Banco banco0 = new Banco("/Y@e{Cc~ 8rm~,8X~W");
      Banco banco1 = new Banco("/Y@e{Cc~ 8rm~,8X~W");
      assertTrue(banco1.equals((Object)banco0));
      
      Long long0 = new Long((-5148L));
      banco1.setId(long0);
      boolean boolean0 = banco0.equals(banco1);
      assertFalse(banco1.equals((Object)banco0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Long long0 = new Long(210L);
      LinkedList<Conta> linkedList0 = new LinkedList<Conta>();
      Banco banco0 = new Banco(long0, "`AA 71*P.mBl^yqU", linkedList0);
      Banco banco1 = new Banco("Banco(id=");
      boolean boolean0 = banco0.equals(banco1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Long long0 = new Long(5422L);
      LinkedList<Conta> linkedList0 = new LinkedList<Conta>();
      Banco banco0 = new Banco(long0, "", linkedList0);
      Conta conta0 = new Conta(long0);
      boolean boolean0 = banco0.equals(conta0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Banco banco0 = new Banco("/Y@e{Cc~ 8rm~,8X~W");
      boolean boolean0 = banco0.equals(banco0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Banco banco0 = new Banco();
      banco0.hashCode();
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Long long0 = new Long(5422L);
      LinkedList<Conta> linkedList0 = new LinkedList<Conta>();
      Banco banco0 = new Banco(long0, "", linkedList0);
      banco0.setNome((String) null);
      banco0.hashCode();
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Banco banco0 = new Banco(", banco=");
      banco0.hashCode();
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Banco banco0 = new Banco();
      Banco banco1 = new Banco("/Y@e{Cc~ 8rm~,8X~W");
      boolean boolean0 = banco0.equals(banco1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Long long0 = new Long(5422L);
      LinkedList<Conta> linkedList0 = new LinkedList<Conta>();
      Banco banco0 = new Banco(long0, "", linkedList0);
      Conta conta0 = new Conta(long0);
      banco0.addConta(conta0);
      assertTrue(linkedList0.contains(conta0));
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Banco banco0 = new Banco(", banco=");
      String string0 = banco0.toString();
      assertEquals("Banco(id=null, nome=, banco=, contas=[])", string0);
  }
}
